### PR TITLE
Jvz re request

### PR DESCRIPTION
**Pull request by jvz**
Seems like whatever happened with the certificate you issued previously doesn't match what I had locally, so I'm recreating another certificate.

### CODE REVIEW

**Comment by olblak** [comment]
I initially deployed the wrong version then fixed in this PR, before recreating your certificate, I would prefer to investigate what's going on, the issue can be elsewhere

**Comment by jvz** [comment]
When I went to verify the public key of my private key, the certificate, and the signing request, the private key didn't match the other two. I didn't save the old private key, so I'll still need this new one issued at some point :)

**Comment by jvz** [comment]
@olblak ping?

**Comment by olblak** [comment]
I opened a different [PR](https://github.com/jenkins-infra/openvpn/pull/86) as I had to first revoke your old certificate before signing a new one, once merged to master, it will generate a new docker image containing your network configuration and the new certificate revocation list.
Once the new docker image is available, it needs to be deployed. Then we can investigate why you could not connect.

**Comment by olblak** [comment]
Everything  should be working, feel free to ping me on IRC or DM

**Pull request closed without merging**
