### PR TITLE
Fix OpenVPN makefile so that it properly works on Windows

### PR DESCRIPTION
**Pull request by oleg-nenashev**
subj.

### CODE REVIEW

**Comment by olblak** [comment]
@oleg-nenashev  Can you correctly rebase on staging, and merge to staging

**Comment by oleg-nenashev** [comment]
It was done in another PR

**Comment by oleg-nenashev** [comment]
Oh, will fix. Maybe you should just make staging a default branch

**Comment by olblak** [comment]
> Oh, will fix. Maybe you should just make staging a default branch

Very good suggestion, I just changed it staging

**Pull request merged**
